table Agents
	lineageTag: f8097c18-21ba-418b-9d24-f7a2c6150fdb

	column FileSystemObjectType
		dataType: string
		isHidden
		lineageTag: 3cd7bfec-467e-4354-89d6-9ad5cae05642
		summarizeBy: none
		sourceColumn: FileSystemObjectType

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: int64
		isHidden
		lineageTag: 56d50cda-5bcf-4780-95ac-9fd66b88e060
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUri
		dataType: string
		isHidden
		lineageTag: 006c5abb-5b42-4a65-9e32-471e513082bb
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUri

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUrl
		dataType: string
		isHidden
		lineageTag: 2bbbd1d5-b318-45c1-a671-9c4a99df781f
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUrl

		annotation SummarizationSetBy = Automatic

	column ContentTypeId
		dataType: string
		isHidden
		lineageTag: a04be8f6-101e-444e-94c7-44ba3b0988b9
		summarizeBy: none
		sourceColumn: ContentTypeId

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 0e61c3a0-47d8-43be-b6a3-9d48a520cc29
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column OData__ColorTag
		dataType: string
		isHidden
		lineageTag: 170ff17d-a534-4015-bfc0-ef1304f6840a
		summarizeBy: none
		sourceColumn: OData__ColorTag

		annotation SummarizationSetBy = Automatic

	column ComplianceAssetId
		dataType: string
		isHidden
		lineageTag: 51ff8883-6bd0-4272-b557-3762d95126a3
		summarizeBy: none
		sourceColumn: ComplianceAssetId

		annotation SummarizationSetBy = Automatic

	column Email_Agent
		dataType: string
		lineageTag: bb4d545b-a4ca-4495-bdf1-a7e749e50e1a
		summarizeBy: none
		sourceColumn: Email_Agent

		annotation SummarizationSetBy = Automatic

	column Date_Recrutement
		dataType: dateTime
		lineageTag: 2020d535-cd4b-4af1-8ec5-a87116189665
		summarizeBy: none
		sourceColumn: Date_Recrutement

		annotation SummarizationSetBy = Automatic

	column Profil_Comportemental_ML
		dataType: string
		lineageTag: 74df3698-306e-42cc-bcb5-73e16484bcea
		summarizeBy: none
		sourceColumn: Profil_Comportemental_ML

		annotation SummarizationSetBy = Automatic

	column Agence_ID0Id
		dataType: int64
		lineageTag: f8fe276f-619b-43c2-9a7c-45cce1a873b9
		summarizeBy: none
		sourceColumn: Agence_ID0Id

		annotation SummarizationSetBy = Automatic

	column 'ID.1'
		dataType: int64
		lineageTag: 1c35a3fd-9d95-4f8f-bbab-168568271cd6
		summarizeBy: none
		sourceColumn: ID.1

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		isHidden
		lineageTag: d723d9fb-4f91-4b4e-8a68-af87659a5ef2
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		isHidden
		lineageTag: 1152223a-d396-4b43-857a-52acb340f7e2
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column AuthorId
		dataType: int64
		isHidden
		lineageTag: eb3d2452-2d7e-44f8-941c-079ed56567e8
		summarizeBy: none
		sourceColumn: AuthorId

		annotation SummarizationSetBy = Automatic

	column EditorId
		dataType: int64
		isHidden
		lineageTag: a8f80f2b-f4f3-49f5-8652-8918ee6f4e28
		summarizeBy: none
		sourceColumn: EditorId

		annotation SummarizationSetBy = Automatic

	column OData__UIVersionString
		dataType: string
		isHidden
		lineageTag: 3f4a0f0b-4245-4420-b58f-7ea391646d3f
		summarizeBy: none
		sourceColumn: OData__UIVersionString

		annotation SummarizationSetBy = Automatic

	column Attachments
		dataType: string
		isHidden
		lineageTag: e5fe1af8-53be-47ac-99bd-bb729d5f09f4
		summarizeBy: none
		sourceColumn: Attachments

		annotation SummarizationSetBy = Automatic

	column GUID
		dataType: string
		isHidden
		lineageTag: d9a4434a-6d35-4292-bae6-c051afaf8a16
		summarizeBy: none
		sourceColumn: GUID

		annotation SummarizationSetBy = Automatic

	partition Agents = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://attakafulia254.sharepoint.com/sites/PortailIntelligentAgents", [ApiVersion = 15]),
				    #"79642daa-9122-459e-85c3-66fbfe1abba5" = Source{[Id="79642daa-9122-459e-85c3-66fbfe1abba5"]}[Items],
				    #"Colonnes renommées" = Table.RenameColumns(#"79642daa-9122-459e-85c3-66fbfe1abba5",{{"ID", "ID.1"}}),
				    #"Types dates modifiés" = Table.TransformColumnTypes(#"Colonnes renommées", {{"Date_Recrutement", type datetime}, {"Modified", type datetime}, {"Created", type datetime}}, "fr-FR")
				in
				    #"Types dates modifiés"

	annotation PBI_ResultType = Table

