table Historique_Demandes
	lineageTag: 83d035c7-f2ee-454a-9c97-7dd585503f05

	column FileSystemObjectType
		dataType: string
		lineageTag: b0e77776-7183-46ad-9672-140727d76ce9
		summarizeBy: none
		sourceColumn: FileSystemObjectType

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: int64
		lineageTag: c13941cd-8173-4a79-a0e4-de2eee41d4a7
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUri
		dataType: string
		lineageTag: 8505d70e-1a00-470a-8a5c-fcba6d88c0e9
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUri

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUrl
		dataType: string
		lineageTag: 730bfef5-84eb-49c0-a66d-0c8c638d5983
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUrl

		annotation SummarizationSetBy = Automatic

	column ContentTypeId
		dataType: string
		lineageTag: 9a5c0cae-e9a1-440a-b10e-dfce328aa703
		summarizeBy: none
		sourceColumn: ContentTypeId

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 48abe0a9-1761-4375-b11e-512da2eaad0d
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column OData__ColorTag
		dataType: string
		lineageTag: dab40b73-18cb-486c-9713-4b0e0b03724a
		summarizeBy: none
		sourceColumn: OData__ColorTag

		annotation SummarizationSetBy = Automatic

	column ComplianceAssetId
		dataType: string
		lineageTag: d1b251c9-9e21-4f9d-963e-455e535c6dc6
		summarizeBy: none
		sourceColumn: ComplianceAssetId

		annotation SummarizationSetBy = Automatic

	column Demande_ID
		dataType: int64
		lineageTag: 2996207c-cb71-4188-9d79-0ba4118a36cd
		summarizeBy: none
		sourceColumn: Demande_ID

		annotation SummarizationSetBy = Automatic

	column Num_Mouvement
		dataType: int64
		lineageTag: 89d97329-62e8-443b-baf9-ccd0e49a1891
		summarizeBy: none
		sourceColumn: Num_Mouvement

		annotation SummarizationSetBy = Automatic

	column Service_A_Ce_Moment
		dataType: string
		lineageTag: 893c6ef0-b53e-473e-b482-c2370a0b31b9
		summarizeBy: none
		sourceColumn: Service_A_Ce_Moment

		annotation SummarizationSetBy = Automatic

	column Gestionnaire_A_Ce_MomentId
		dataType: int64
		lineageTag: 57de5c3f-95fd-47fc-b85e-124e23e712cb
		summarizeBy: none
		sourceColumn: Gestionnaire_A_Ce_MomentId

		annotation SummarizationSetBy = Automatic

	column Gestionnaire_A_Ce_MomentStringId
		dataType: string
		lineageTag: 8186977c-2d44-42c6-920d-07b110201577
		summarizeBy: none
		sourceColumn: Gestionnaire_A_Ce_MomentStringId

		annotation SummarizationSetBy = Automatic

	column Statut_A_Ce_Moment
		dataType: string
		lineageTag: 1d1fc75c-91dd-4f22-b455-d2f5b57a851a
		summarizeBy: none
		sourceColumn: Statut_A_Ce_Moment

		annotation SummarizationSetBy = Automatic

	column Date_Debut_Etape
		dataType: dateTime
		lineageTag: a65f9f59-1be5-4be0-8916-25312cf18937
		summarizeBy: none
		sourceColumn: Date_Debut_Etape

		annotation SummarizationSetBy = Automatic

	column Date_Fin_Etape
		dataType: dateTime
		lineageTag: 06f2b7d9-3f10-47ee-a987-da4e1439532c
		summarizeBy: none
		sourceColumn: Date_Fin_Etape

		annotation SummarizationSetBy = Automatic

	column ActionneurId
		dataType: int64
		lineageTag: c4d469ae-f1c0-462e-ae6c-aa816ce0cccd
		summarizeBy: none
		sourceColumn: ActionneurId

		annotation SummarizationSetBy = Automatic

	column ActionneurStringId
		dataType: string
		lineageTag: fba5c2cc-4a25-4d4b-9edc-194ba63602be
		summarizeBy: none
		sourceColumn: ActionneurStringId

		annotation SummarizationSetBy = Automatic

	column Commentaire_Action
		dataType: string
		lineageTag: 169ba1e2-4a84-4ed9-a5b5-1a6f64f1e9d3
		summarizeBy: none
		sourceColumn: Commentaire_Action

		annotation SummarizationSetBy = Automatic

	column Createur_DemandeId
		dataType: int64
		lineageTag: e7ce7620-0d23-4d5f-9668-8972460479c0
		summarizeBy: none
		sourceColumn: Createur_DemandeId

		annotation SummarizationSetBy = Automatic

	column Createur_DemandeStringId
		dataType: string
		lineageTag: 5378c0bc-60bc-4585-a064-0ae289596498
		summarizeBy: none
		sourceColumn: Createur_DemandeStringId

		annotation SummarizationSetBy = Automatic

	column Type_Modification
		dataType: string
		lineageTag: d436f711-741d-4606-8bc2-39a53ef4e4b3
		summarizeBy: none
		sourceColumn: Type_Modification

		annotation SummarizationSetBy = Automatic

	column 'ID.1'
		dataType: int64
		lineageTag: 4c0ddd61-2e1f-4370-8dd6-3f50a03f1d0e
		summarizeBy: none
		sourceColumn: ID.1

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		lineageTag: bfffa7a8-5cee-4790-a49c-0c45db6b1569
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		lineageTag: 05ab7525-927e-4c6d-b7e9-14916143b5bb
		summarizeBy: none
		sourceColumn: Created

		annotation SummarizationSetBy = Automatic

	column AuthorId
		dataType: int64
		lineageTag: 904eaa1c-5cc2-45ef-9be5-c416b99aea8d
		summarizeBy: none
		sourceColumn: AuthorId

		annotation SummarizationSetBy = Automatic

	column EditorId
		dataType: int64
		lineageTag: 106d21a6-45d4-4b07-b338-0472b7f90760
		summarizeBy: none
		sourceColumn: EditorId

		annotation SummarizationSetBy = Automatic

	column OData__UIVersionString
		dataType: string
		lineageTag: 127569ed-9078-4834-9f2f-b9340536fe6b
		summarizeBy: none
		sourceColumn: OData__UIVersionString

		annotation SummarizationSetBy = Automatic

	column Attachments
		dataType: string
		lineageTag: 03be0a93-2b3a-42d4-bb80-3c960efdc72c
		summarizeBy: none
		sourceColumn: Attachments

		annotation SummarizationSetBy = Automatic

	column GUID
		dataType: string
		lineageTag: d4e63573-c5ae-4abc-89eb-9106e5710d6f
		summarizeBy: none
		sourceColumn: GUID

		annotation SummarizationSetBy = Automatic

	partition Historique_Demandes = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://attakafulia254.sharepoint.com/sites/PortailIntelligentAgents", [ApiVersion = 15]),
				    #"711be3b1-2c60-4936-b580-9e20ceac050c" = Source{[Id="711be3b1-2c60-4936-b580-9e20ceac050c"]}[Items],
				    #"Colonnes renommées" = Table.RenameColumns(#"711be3b1-2c60-4936-b580-9e20ceac050c",{{"ID", "ID.1"}}),
				    #"Types dates modifiés" = Table.TransformColumnTypes(#"Colonnes renommées", {{"Date_Debut_Etape", type datetime}, {"Date_Fin_Etape", type datetime}, {"Modified", type datetime}, {"Created", type datetime}}, "fr-FR")
				in
				    #"Types dates modifiés"

	annotation PBI_ResultType = Table

